alias: Github backup
description: Push configuration to github repo [user]/[repository]
trigger:
  - at: '23:59:00'
    platform: time
condition: []
action:
  - service: shell_command.push_to_github
    data: {}
mode: single